export const MANA_OPTIONS = [
    { key: '0', value: '0 maná' },
    { key: '1', value: '1 maná' },
    { key: '2', value: '2 maná' },
    { key: '3', value: '3 maná' },
    { key: '4', value: '4 maná' },
    { key: '5', value: '5 maná' },
    { key: '6', value: '6 maná' },
    { key: '7', value: '7 maná' },
    { key: '8', value: '8 maná' },
    { key: '9', value: '9 maná' },
    { key: '10', value: '10 maná' },
    { key: '11', value: '11 maná' },
    { key: '12', value: '12 maná' },
    { key: '13', value: '13 maná' },
    { key: '14', value: '14 maná' },
    { key: '15', value: '15 maná' },
    { key: '16', value: '16 maná' },
  ];
  