export const MANA_OPTIONS = [
    { key: '{W}', value: '1 maná blanco' },
    { key: '{U}', value: '1 maná azul' },
    { key: '{B}', value: '1 maná negro' },
    { key: '{R}', value: '1 maná rojo' },
    { key: '{G}', value: '1 maná verde' },
    { key: '{C}', value: '1 maná incoloro' },
    { key: '{X}', value: 'X maná genérico' },
    { key: '{0}', value: '0 maná' },
    { key: '{1}', value: '1 maná genérico' },
    { key: '{2}', value: '2 maná genérico' },
    { key: '{3}', value: '3 maná genérico' },
    { key: '{4}', value: '4 maná genérico' },
    { key: '{5}', value: '5 maná genérico' },
    { key: '{6}', value: '6 maná genérico' },
    { key: '{7}', value: '7 maná genérico' },
    { key: '{8}', value: '8 maná genérico' },
    { key: '{9}', value: '9 maná genérico' },
    { key: '{10}', value: '10 maná genérico' },
    { key: '{11}', value: '11 maná genérico' },
    { key: '{12}', value: '12 maná genérico' },
    { key: '{13}', value: '13 maná genérico' },
    { key: '{14}', value: '14 maná genérico' },
    { key: '{15}', value: '15 maná genérico' },
    { key: '{16}', value: '16 maná genérico' },
    { key: '{W/U}', value: '1 maná blanco o azul' },
    { key: '{W/B}', value: '1 maná blanco o negro' },
    { key: '{B/R}', value: '1 maná negro o rojo' },
    { key: '{B/G}', value: '1 maná negro o verde' },
    { key: '{U/B}', value: '1 maná azul o negro' },
    { key: '{U/R}', value: '1 maná azul o rojo' },
    { key: '{R/G}', value: '1 maná rojo o verde' },
    { key: '{R/W}', value: '1 maná rojo o blanco' },
    { key: '{G/W}', value: '1 maná verde o blanco' },
    { key: '{G/U}', value: '1 maná verde o azul' },
    { key: '{G/U/P}', value: '1 maná verde, 1 maná azul o 2 vidas' },
    { key: '{G/W/P}', value: '1 maná verde, 1 maná blanco o 2 vidas' },
    { key: '{C/W}', value: '1 maná incoloro o 1 maná blanco' },
    { key: '{C/U}', value: '1 maná incoloro o 1 maná azul' },
    { key: '{C/B}', value: '1 maná incoloro o 1 maná negro' },
    { key: '{C/R}', value: '1 maná incoloro o 1 maná rojo' },
    { key: '{C/G}', value: '1 maná incoloro o 1 maná verde' },
    { key: '{2/W}', value: '2 maná genérico o 1 maná blanco' },
    { key: '{2/U}', value: '2 maná genérico o 1 maná azul' },
    { key: '{2/B}', value: '2 maná genérico o 1 maná negro' },
    { key: '{2/R}', value: '2 maná genérico o 1 maná rojo' },
    { key: '{2/G}', value: '2 maná genérico o 1 maná verde' },
    { key: '{W/P}', value: '1 maná blanco o 2 vidas' },
    { key: '{U/P}', value: '1 maná azul o 2 vidas' },
    { key: '{B/P}', value: '1 maná negro o 2 vidas' },
    { key: '{R/P}', value: '1 maná rojo o 2 vidas' },
    { key: '{G/P}', value: '1 maná verde o 2 vidas' },
    { key: '{S}', value: '1 maná de nieve' },
  ];
  