export const TYPE_OPTIONS = [
    { key: 'artifact', value: 'Artifact' },
    { key: 'basic', value: 'Basic' },
    { key: 'battle', value: 'Battle' },
    { key: 'conspiracy', value: 'Conspiracy' },
    { key: 'creature', value: 'Creature' },
    { key: 'enchantment', value: 'Enchantment' },
    { key: 'instant', value: 'Instant' },
    { key: 'kindred', value: 'Kindred' },
    { key: 'land', value: 'Land' },
    { key: 'legendary', value: 'Legendary' },
    { key: 'planeswalker', value: 'Planeswalker' },
    { key: 'snow', value: 'Snow' },
    { key: 'sorcery', value: 'Sorcery' },
    { key: 'tribal', value: 'Tribal' },
    { key: 'world', value: 'World' },
];
